"""edited code db

Revision ID: 2c31a3792a32
Revises: 4d35f8c3a798
Create Date: 2023-06-23 21:02:44.046713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c31a3792a32'
down_revision = '4d35f8c3a798'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'recovery_code', ['code'])
    op.create_unique_constraint(None, 'recovery_code', ['email'])
    op.drop_column('recovery_code', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_code', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recovery_code', type_='unique')
    op.drop_constraint(None, 'recovery_code', type_='unique')
    # ### end Alembic commands ###
