"""balance fix

Revision ID: 39f7599da5e6
Revises: 4c5968d99e6c
Create Date: 2023-06-22 22:25:24.163733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f7599da5e6'
down_revision = '4c5968d99e6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
