"""Product changes

Revision ID: 6be15f03e04a
Revises: f5beb7061057
Create Date: 2023-06-29 00:49:27.602044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be15f03e04a'
down_revision = 'f5beb7061057'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
